version: '3.8'
services:
  postgres:
    image: 'postgres'
    env_file:
      - ./.env
  showerthoughts:
    build: ./
    ports:
      - '3030:3030'
    env_file:
      - ./.env
    depends_on:
      - postgres